import pandas as pd
import numpy as np
import yfinance as yf
from typing import Dict, List, Tuple, Optional
import streamlit as st
from datetime import datetime, timedelta
import time
import json
import requests
from dataclasses import dataclass
import threading
import queue

@dataclass
class TradePosition:
    """Represents a trading position"""
    symbol: str
    action: str  # BUY or SELL
    price: float
    quantity: int
    timestamp: datetime
    stop_loss: float
    target_price: float
    confidence: float
    reasoning: str

@dataclass
class MarketSignal:
    """Represents a market signal generated by AI"""
    symbol: str
    signal_type: str  # BUY, SELL, HOLD
    confidence: float
    reasoning: str
    technical_score: float
    fundamental_score: float
    momentum_score: float
    risk_level: str
    target_price: float
    stop_loss: float
    timestamp: datetime

class PerpetualAITrader:
    """Advanced AI Trading System with Continuous Market Analysis"""
    
    def __init__(self):
        self.portfolio = {}
        self.trade_history = []
        self.market_signals = []
        self.learning_data = {}
        self.risk_parameters = {
            'max_position_size': 0.05,  # 5% of portfolio per position
            'stop_loss_pct': 0.08,      # 8% stop loss
            'take_profit_pct': 0.20,    # 20% take profit
            'max_daily_loss': 0.02,     # 2% max daily loss
            'risk_free_rate': 0.05      # 5% risk-free rate
        }
        
        # AI learning parameters
        self.success_patterns = {}
        self.failure_patterns = {}
        self.market_psychology_indicators = {}
        
        # Continuous analysis parameters
        self.monitoring_active = False
        self.analysis_queue = queue.Queue()
        
    def start_perpetual_analysis(self, stock_universe: List[str]) -> None:
        """Start continuous market monitoring and analysis"""
        self.monitoring_active = True
        st.info("🤖 AI Trader: Starting perpetual market analysis...")
        
        # Create background thread for continuous monitoring
        def continuous_monitor():
            while self.monitoring_active:
                try:
                    self._perform_market_sweep(stock_universe)
                    time.sleep(300)  # Analyze every 5 minutes
                except Exception as e:
                    st.error(f"Monitoring error: {str(e)}")
                    time.sleep(60)
        
        # Start monitoring thread
        monitor_thread = threading.Thread(target=continuous_monitor, daemon=True)
        monitor_thread.start()
    
    def _perform_market_sweep(self, symbols: List[str]) -> None:
        """Perform comprehensive market analysis sweep"""
        current_time = datetime.now()
        
        for symbol in symbols:
            try:
                # Fetch real-time data
                ticker = yf.Ticker(symbol)
                info = ticker.info
                hist_data = ticker.history(period="3mo")
                
                if hist_data.empty or not info:
                    continue
                
                # Generate AI signal
                signal = self._generate_ai_signal(symbol, info, hist_data)
                
                if signal and signal.confidence > 0.75:  # High confidence signals only
                    self.market_signals.append(signal)
                    
                    # Execute trade if conditions are met
                    if signal.signal_type == "BUY" and self._should_execute_trade(signal):
                        self._execute_virtual_trade(signal)
                
            except Exception as e:
                continue
    
    def _generate_ai_signal(self, symbol: str, stock_info: Dict, hist_data: pd.DataFrame) -> Optional[MarketSignal]:
        """Generate sophisticated AI trading signal"""
        try:
            # Technical Analysis
            technical_score = self._analyze_technical_patterns(hist_data)
            
            # Fundamental Analysis
            fundamental_score = self._analyze_fundamentals(stock_info)
            
            # Momentum Analysis
            momentum_score = self._analyze_momentum(hist_data)
            
            # Market Psychology
            psychology_score = self._analyze_market_psychology(symbol, hist_data)
            
            # Combine scores with AI weighting
            combined_score = (
                technical_score * 0.35 +
                fundamental_score * 0.25 +
                momentum_score * 0.25 +
                psychology_score * 0.15
            )
            
            # Determine signal type
            if combined_score >= 75:
                signal_type = "BUY"
                confidence = min(combined_score / 100, 0.95)
            elif combined_score <= 30:
                signal_type = "SELL"
                confidence = min((100 - combined_score) / 100, 0.95)
            else:
                signal_type = "HOLD"
                confidence = 0.5
            
            # Calculate target price and stop loss
            current_price = stock_info.get('regularMarketPrice', 0)
            if current_price == 0:
                return None
            
            target_price, stop_loss = self._calculate_price_targets(
                current_price, signal_type, hist_data
            )
            
            # Generate reasoning
            reasoning = self._generate_signal_reasoning(
                technical_score, fundamental_score, momentum_score, psychology_score
            )
            
            # Risk assessment
            risk_level = self._assess_trade_risk(stock_info, hist_data)
            
            return MarketSignal(
                symbol=symbol,
                signal_type=signal_type,
                confidence=confidence,
                reasoning=reasoning,
                technical_score=technical_score,
                fundamental_score=fundamental_score,
                momentum_score=momentum_score,
                risk_level=risk_level,
                target_price=target_price,
                stop_loss=stop_loss,
                timestamp=datetime.now()
            )
            
        except Exception as e:
            return None
    
    def _analyze_technical_patterns(self, hist_data: pd.DataFrame) -> float:
        """Advanced technical pattern recognition"""
        if len(hist_data) < 50:
            return 50
        
        close_prices = hist_data['Close']
        volume = hist_data['Volume']
        
        score = 50  # Neutral start
        
        # Moving Average Analysis
        ma20 = close_prices.rolling(20).mean()
        ma50 = close_prices.rolling(50).mean()
        
        current_price = close_prices.iloc[-1]
        current_ma20 = ma20.iloc[-1]
        current_ma50 = ma50.iloc[-1]
        
        # Price above moving averages
        if current_price > current_ma20 > current_ma50:
            score += 15
        elif current_price > current_ma20:
            score += 8
        
        # Golden Cross pattern
        if (ma20.iloc[-1] > ma50.iloc[-1] and 
            ma20.iloc[-2] <= ma50.iloc[-2]):
            score += 20
        
        # Volume confirmation
        avg_volume = volume.rolling(20).mean().iloc[-1]
        current_volume = volume.iloc[-1]
        if current_volume > avg_volume * 1.5:
            score += 10
        
        # RSI analysis
        delta = close_prices.diff()
        gain = (delta.where(delta > 0, 0)).rolling(14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(14).mean()
        rs = gain / loss
        rsi = 100 - (100 / (1 + rs))
        current_rsi = rsi.iloc[-1]
        
        if 30 < current_rsi < 70:
            score += 8
        elif current_rsi < 30:
            score += 12  # Oversold opportunity
        
        # MACD analysis
        ema12 = close_prices.ewm(span=12).mean()
        ema26 = close_prices.ewm(span=26).mean()
        macd = ema12 - ema26
        signal_line = macd.ewm(span=9).mean()
        
        if macd.iloc[-1] > signal_line.iloc[-1] and macd.iloc[-2] <= signal_line.iloc[-2]:
            score += 15
        
        # Bollinger Bands squeeze detection
        bb_period = 20
        bb_std = 2
        bb_middle = close_prices.rolling(bb_period).mean()
        bb_std_dev = close_prices.rolling(bb_period).std()
        bb_upper = bb_middle + (bb_std_dev * bb_std)
        bb_lower = bb_middle - (bb_std_dev * bb_std)
        
        # Squeeze detection (low volatility before breakout)
        bb_width = (bb_upper - bb_lower) / bb_middle
        if bb_width.iloc[-1] < bb_width.rolling(20).mean().iloc[-1] * 0.8:
            score += 10  # Potential breakout setup
        
        return min(100, max(0, score))
    
    def _analyze_fundamentals(self, stock_info: Dict) -> float:
        """Advanced fundamental analysis"""
        score = 50
        
        # P/E Ratio Analysis
        pe_ratio = stock_info.get('trailingPE', 0)
        industry_pe = stock_info.get('industry', '')
        
        if 0 < pe_ratio < 15:
            score += 20
        elif 15 <= pe_ratio < 25:
            score += 10
        elif pe_ratio > 40:
            score -= 15
        
        # Growth Metrics
        revenue_growth = stock_info.get('revenueGrowth', 0)
        earnings_growth = stock_info.get('earningsGrowth', 0)
        
        if revenue_growth > 0.20:  # 20%+ revenue growth
            score += 15
        elif revenue_growth > 0.10:
            score += 8
        
        if earnings_growth > 0.25:  # 25%+ earnings growth
            score += 15
        elif earnings_growth > 0.15:
            score += 8
        
        # Profitability
        profit_margin = stock_info.get('profitMargins', 0)
        roe = stock_info.get('returnOnEquity', 0)
        
        if profit_margin > 0.20:  # 20%+ profit margin
            score += 10
        elif profit_margin > 0.10:
            score += 5
        
        if roe > 0.15:  # 15%+ ROE
            score += 10
        elif roe > 0.10:
            score += 5
        
        # Financial Health
        debt_to_equity = stock_info.get('debtToEquity', 0)
        current_ratio = stock_info.get('currentRatio', 0)
        
        if debt_to_equity < 30:
            score += 8
        elif debt_to_equity > 100:
            score -= 10
        
        if current_ratio > 1.5:
            score += 5
        
        # Market Position
        market_cap = stock_info.get('marketCap', 0)
        if market_cap > 10e9:  # Large cap stability
            score += 5
        elif market_cap < 2e9:  # Small cap growth potential
            score += 3
        
        return min(100, max(0, score))
    
    def _analyze_momentum(self, hist_data: pd.DataFrame) -> float:
        """Momentum and trend analysis"""
        if len(hist_data) < 30:
            return 50
        
        close_prices = hist_data['Close']
        score = 50
        
        # Price momentum over multiple timeframes
        current_price = close_prices.iloc[-1]
        
        # 5-day momentum
        price_5d = close_prices.iloc[-6] if len(close_prices) > 5 else current_price
        momentum_5d = (current_price - price_5d) / price_5d
        
        # 20-day momentum
        price_20d = close_prices.iloc[-21] if len(close_prices) > 20 else current_price
        momentum_20d = (current_price - price_20d) / price_20d
        
        # 60-day momentum
        price_60d = close_prices.iloc[-61] if len(close_prices) > 60 else current_price
        momentum_60d = (current_price - price_60d) / price_60d
        
        # Score momentum
        if momentum_5d > 0.03:  # 3%+ in 5 days
            score += 15
        elif momentum_5d > 0:
            score += 5
        
        if momentum_20d > 0.15:  # 15%+ in 20 days
            score += 20
        elif momentum_20d > 0.05:
            score += 10
        elif momentum_20d > 0:
            score += 5
        
        if momentum_60d > 0.30:  # 30%+ in 60 days
            score += 15
        elif momentum_60d > 0.10:
            score += 8
        
        # Acceleration analysis
        if momentum_5d > momentum_20d / 4:  # Accelerating momentum
            score += 10
        
        return min(100, max(0, score))
    
    def _analyze_market_psychology(self, symbol: str, hist_data: pd.DataFrame) -> float:
        """Market psychology and sentiment analysis"""
        score = 50
        
        if len(hist_data) < 20:
            return score
        
        # Volume analysis for institutional interest
        volume = hist_data['Volume']
        avg_volume = volume.rolling(20).mean()
        
        recent_volume = volume.tail(5).mean()
        if recent_volume > avg_volume.iloc[-1] * 1.3:
            score += 15  # Increasing institutional interest
        
        # Price action psychology
        close_prices = hist_data['Close']
        high_prices = hist_data['High']
        low_prices = hist_data['Low']
        
        # Breakout detection
        recent_high = high_prices.rolling(20).max().iloc[-1]
        current_price = close_prices.iloc[-1]
        
        if current_price > recent_high * 0.98:  # Near 20-day high
            score += 12
        
        # Support level analysis
        recent_low = low_prices.rolling(20).min().iloc[-1]
        if current_price > recent_low * 1.10:  # Well above recent lows
            score += 8
        
        # Volatility analysis
        returns = close_prices.pct_change().dropna()
        volatility = returns.std()
        
        if 0.02 < volatility < 0.05:  # Optimal volatility range
            score += 8
        elif volatility > 0.08:  # High volatility risk
            score -= 10
        
        return min(100, max(0, score))
    
    def _calculate_price_targets(self, current_price: float, signal_type: str, hist_data: pd.DataFrame) -> Tuple[float, float]:
        """Calculate intelligent price targets and stop losses"""
        if signal_type == "BUY":
            # Calculate target based on volatility and support/resistance
            volatility = hist_data['Close'].pct_change().std() * np.sqrt(252)
            
            # Target price (conservative approach)
            target_multiplier = 1 + min(0.25, volatility * 0.8)
            target_price = current_price * target_multiplier
            
            # Stop loss (risk management)
            stop_loss_multiplier = 1 - min(0.12, volatility * 0.5)
            stop_loss = current_price * stop_loss_multiplier
            
        else:  # SELL signal
            target_price = current_price * 0.90  # 10% downside target
            stop_loss = current_price * 1.05   # 5% upside stop
        
        return target_price, stop_loss
    
    def _generate_signal_reasoning(self, tech_score: float, fund_score: float, 
                                  momentum_score: float, psychology_score: float) -> str:
        """Generate human-readable reasoning for the signal"""
        reasons = []
        
        if tech_score > 70:
            reasons.append("Strong technical patterns detected")
        elif tech_score > 60:
            reasons.append("Positive technical indicators")
        
        if fund_score > 70:
            reasons.append("Excellent fundamental metrics")
        elif fund_score > 60:
            reasons.append("Solid fundamental foundation")
        
        if momentum_score > 70:
            reasons.append("Strong price momentum")
        elif momentum_score > 60:
            reasons.append("Positive momentum trend")
        
        if psychology_score > 70:
            reasons.append("Favorable market sentiment")
        elif psychology_score > 60:
            reasons.append("Supportive market psychology")
        
        if not reasons:
            reasons.append("Mixed signals - proceed with caution")
        
        return "; ".join(reasons)
    
    def _assess_trade_risk(self, stock_info: Dict, hist_data: pd.DataFrame) -> str:
        """Assess overall trade risk level"""
        risk_factors = 0
        
        # Market cap risk
        market_cap = stock_info.get('marketCap', 0)
        if market_cap < 2e9:
            risk_factors += 2
        elif market_cap < 10e9:
            risk_factors += 1
        
        # Volatility risk
        if len(hist_data) >= 30:
            returns = hist_data['Close'].pct_change().dropna()
            volatility = returns.std() * np.sqrt(252)
            if volatility > 0.6:
                risk_factors += 2
            elif volatility > 0.4:
                risk_factors += 1
        
        # Financial health risk
        debt_to_equity = stock_info.get('debtToEquity', 0)
        if debt_to_equity > 100:
            risk_factors += 1
        
        # Penny stock risk
        current_price = stock_info.get('regularMarketPrice', 0)
        if current_price <= 5:
            risk_factors += 2
        
        if risk_factors >= 4:
            return "High"
        elif risk_factors >= 2:
            return "Medium"
        else:
            return "Low"
    
    def _should_execute_trade(self, signal: MarketSignal) -> bool:
        """Determine if trade should be executed based on risk management"""
        # Check portfolio constraints
        if len(self.portfolio) >= 10:  # Max 10 positions
            return False
        
        # Check confidence threshold
        if signal.confidence < 0.80:
            return False
        
        # Check risk level
        if signal.risk_level == "High" and signal.confidence < 0.90:
            return False
        
        # Check if already holding position
        if signal.symbol in self.portfolio:
            return False
        
        return True
    
    def _execute_virtual_trade(self, signal: MarketSignal) -> None:
        """Execute virtual trade for backtesting and learning"""
        current_price = signal.target_price  # Using target as entry for demo
        
        # Calculate position size based on risk management
        portfolio_value = 100000  # $100k virtual portfolio
        risk_amount = portfolio_value * self.risk_parameters['max_position_size']
        
        # Calculate shares based on stop loss risk
        price_risk = abs(current_price - signal.stop_loss)
        shares = int(risk_amount / price_risk) if price_risk > 0 else 100
        
        trade = TradePosition(
            symbol=signal.symbol,
            action=signal.signal_type,
            price=current_price,
            quantity=shares,
            timestamp=datetime.now(),
            stop_loss=signal.stop_loss,
            target_price=signal.target_price,
            confidence=signal.confidence,
            reasoning=signal.reasoning
        )
        
        self.portfolio[signal.symbol] = trade
        self.trade_history.append(trade)
    
    def get_latest_signals(self, limit: int = 20) -> List[MarketSignal]:
        """Get latest high-confidence trading signals"""
        # Sort by timestamp and confidence
        sorted_signals = sorted(
            self.market_signals,
            key=lambda x: (x.timestamp, x.confidence),
            reverse=True
        )
        
        return sorted_signals[:limit]
    
    def get_active_positions(self) -> Dict[str, TradePosition]:
        """Get current active trading positions"""
        return self.portfolio.copy()
    
    def get_performance_metrics(self) -> Dict:
        """Calculate trading performance metrics"""
        if not self.trade_history:
            return {}
        
        total_trades = len(self.trade_history)
        buy_trades = [t for t in self.trade_history if t.action == "BUY"]
        
        return {
            'total_trades': total_trades,
            'buy_signals': len(buy_trades),
            'avg_confidence': np.mean([t.confidence for t in self.trade_history]),
            'active_positions': len(self.portfolio),
            'last_signal_time': self.market_signals[-1].timestamp if self.market_signals else None
        }
    
    def identify_breakout_candidates(self, market_data: Dict[str, Dict]) -> List[Dict]:
        """Identify stocks likely to breakout before they actually do"""
        breakout_candidates = []
        
        for symbol, stock_info in market_data.items():
            try:
                ticker = yf.Ticker(symbol)
                hist_data = ticker.history(period="6mo")
                
                if hist_data.empty:
                    continue
                
                # Breakout pattern detection
                breakout_score = self._calculate_breakout_probability(hist_data, stock_info)
                
                if breakout_score >= 75:  # High probability breakout
                    current_price = stock_info.get('regularMarketPrice', 0)
                    
                    breakout_candidates.append({
                        'symbol': symbol,
                        'company_name': stock_info.get('longName', symbol),
                        'current_price': current_price,
                        'breakout_score': breakout_score,
                        'volume_surge': self._calculate_volume_surge(hist_data),
                        'consolidation_days': self._calculate_consolidation_period(hist_data),
                        'resistance_level': self._find_resistance_level(hist_data),
                        'target_price': current_price * 1.2,  # 20% target
                        'market_cap': stock_info.get('marketCap', 0),
                        'sector': stock_info.get('sector', 'Unknown')
                    })
                    
            except Exception as e:
                continue
        
        # Sort by breakout score
        breakout_candidates.sort(key=lambda x: x['breakout_score'], reverse=True)
        
        return breakout_candidates
    
    def _calculate_breakout_probability(self, hist_data: pd.DataFrame, stock_info: Dict) -> float:
        """Calculate probability of imminent breakout"""
        if len(hist_data) < 60:
            return 0
        
        score = 0
        close_prices = hist_data['Close']
        volume = hist_data['Volume']
        high_prices = hist_data['High']
        
        # 1. Consolidation pattern detection
        recent_high = high_prices.rolling(20).max().iloc[-1]
        recent_range = (high_prices.rolling(20).max() - hist_data['Low'].rolling(20).min()).iloc[-1]
        price_compression = recent_range / recent_high
        
        if price_compression < 0.10:  # Tight consolidation
            score += 25
        elif price_compression < 0.15:
            score += 15
        
        # 2. Volume accumulation
        recent_volume = volume.tail(10).mean()
        previous_volume = volume.head(-10).tail(20).mean()
        volume_increase = recent_volume / previous_volume if previous_volume > 0 else 1
        
        if volume_increase > 1.5:
            score += 20
        elif volume_increase > 1.2:
            score += 10
        
        # 3. Moving average convergence
        ma20 = close_prices.rolling(20).mean()
        ma50 = close_prices.rolling(50).mean()
        
        current_price = close_prices.iloc[-1]
        if current_price > ma20.iloc[-1] > ma50.iloc[-1]:
            score += 15
        
        # 4. RSI setup
        delta = close_prices.diff()
        gain = (delta.where(delta > 0, 0)).rolling(14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(14).mean()
        rs = gain / loss
        rsi = 100 - (100 / (1 + rs))
        
        current_rsi = rsi.iloc[-1]
        if 45 < current_rsi < 65:  # Neutral RSI ready for move
            score += 15
        
        # 5. Fundamental catalyst
        earnings_growth = stock_info.get('earningsGrowth', 0)
        revenue_growth = stock_info.get('revenueGrowth', 0)
        
        if earnings_growth > 0.20 or revenue_growth > 0.15:
            score += 15
        
        # 6. Market cap considerations
        market_cap = stock_info.get('marketCap', 0)
        if 1e9 < market_cap < 50e9:  # Sweet spot for breakouts
            score += 10
        
        return min(100, score)
    
    def _calculate_volume_surge(self, hist_data: pd.DataFrame) -> float:
        """Calculate recent volume surge percentage"""
        volume = hist_data['Volume']
        recent_volume = volume.tail(5).mean()
        average_volume = volume.head(-5).mean()
        
        return ((recent_volume - average_volume) / average_volume * 100) if average_volume > 0 else 0
    
    def _calculate_consolidation_period(self, hist_data: pd.DataFrame) -> int:
        """Calculate number of days in consolidation"""
        close_prices = hist_data['Close']
        high_prices = hist_data['High']
        low_prices = hist_data['Low']
        
        # Find consolidation pattern
        for days in range(10, 60):
            if len(hist_data) < days:
                continue
                
            period_high = high_prices.tail(days).max()
            period_low = low_prices.tail(days).min()
            price_range = (period_high - period_low) / period_high
            
            if price_range < 0.12:  # 12% range indicates consolidation
                return days
        
        return 0
    
    def _find_resistance_level(self, hist_data: pd.DataFrame) -> float:
        """Find key resistance level"""
        high_prices = hist_data['High']
        
        # Find recent highs that acted as resistance
        resistance_levels = []
        
        for i in range(len(high_prices) - 20, len(high_prices) - 5):
            if i < 5:
                continue
                
            current_high = high_prices.iloc[i]
            
            # Check if this high was tested multiple times
            similar_highs = 0
            for j in range(max(0, i-20), min(len(high_prices), i+10)):
                if abs(high_prices.iloc[j] - current_high) / current_high < 0.02:
                    similar_highs += 1
            
            if similar_highs >= 2:
                resistance_levels.append(current_high)
        
        return max(resistance_levels) if resistance_levels else high_prices.tail(20).max()